Repository Extenza-Academy/WebDev-100_2021-Q1, pull requests merged in 2021-01, with the labels that each got.

#60 Update 2.3.6.md
  .github/ISSUE_TEMPLATE/2.3.6.md
Labels: 0. Org, e/1

#61 Created templates for Terrarium
  .github/ISSUE_TEMPLATE/3.1.1.md
  .github/ISSUE_TEMPLATE/3.1.2.md
  .github/ISSUE_TEMPLATE/3.1.3.md
  .github/ISSUE_TEMPLATE/3.1.4.md
  .github/ISSUE_TEMPLATE/3.1.5.md
  .github/ISSUE_TEMPLATE/3.1.6.md
  .github/ISSUE_TEMPLATE/3.2.1.md
  .github/ISSUE_TEMPLATE/3.2.2.md
  .github/ISSUE_TEMPLATE/3.2.3.md
  .github/ISSUE_TEMPLATE/3.2.4.md
  .github/ISSUE_TEMPLATE/3.2.5.md
  .github/ISSUE_TEMPLATE/3.2.6.md
  .github/ISSUE_TEMPLATE/3.3.1.md
  .github/ISSUE_TEMPLATE/3.3.2.md
  .github/ISSUE_TEMPLATE/3.3.3.md
  .github/ISSUE_TEMPLATE/3.3.4.md
  .github/ISSUE_TEMPLATE/3.3.5.md
  .github/ISSUE_TEMPLATE/3.3.6.md
Labels: 0. Org, 3. Terrarium, e/1

#87 Fix image link in `3.1.1.`
  .github/ISSUE_TEMPLATE/3.1.1.md
Labels: 0. Org

#92 Fixed the link to the image for Part 3
  .github/ISSUE_TEMPLATE/3.1.2.md
  .github/ISSUE_TEMPLATE/3.2.1.md
  .github/ISSUE_TEMPLATE/3.2.2.md
  .github/ISSUE_TEMPLATE/3.2.3.md
  .github/ISSUE_TEMPLATE/3.3.1.md
  .github/ISSUE_TEMPLATE/3.3.2.md
Labels: 0. Org
